# Camera configuration
- ros_topic_name: "camera/image_raw"
  gz_topic_name: "world/default/model/x500_gimbal_0/link/camera_link/sensor/camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
  lazy: false

#  # LIDAR configuration
#- ros_topic_name: "scan"
#  gz_topic_name: "scan"
#  ros_type_name: "sensor_msgs/msg/LaserScan"
#  gz_type_name: "gz.msgs.LaserScan"
#  direction: GZ_TO_ROS
#  lazy: false
#
#- ros_topic_name: "scan/points"
#  gz_topic_name: "scan/points"
#  ros_type_name: "sensor_msgs/msg/PointCloud2"
#  gz_type_name: "gz.msgs.PointCloudPacked"
#  direction: GZ_TO_ROS
#  lazy: false
#
## IMU configuration
#- ros_topic_name: "imu"
#  gz_topic_name: "imu/data"
#  ros_type_name: "sensor_msgs/msg/Imu"
#  gz_type_name: "gz.msgs.IMU"
#  direction: GZ_TO_ROS
#  lazy: false
#
#
## Clock configuration
#- ros_topic_name: "clock"
#  gz_topic_name: "clock"
#  ros_type_name: "rosgraph_msgs/msg/Clock"
#  gz_type_name: "gz.msgs.Clock"
#  direction: GZ_TO_ROS
#  lazy: false
